# my_numbers=list(range(10))
# print(my_numbers)
# my_numbers=(range(10))
# print(my_numbers)
# my_numbers=list(range(5,10))
# print(my_numbers)
# my_numbers=list(range(4,20,4))
# print(my_numbers)
my_numbers=list(range(4,20,4))
print(my_numbers)
